### ISSUE TITLE
"Minas Gerais" aparece com o label "Rio de Janeiro"

### ISSUE THREAD

**Issue by Caboverde** [gdmarmerola/realtime_r0_brazil#1]

**Comment by gdmarmerola** [comment]
Valeu pelo toque! 

Esse fix fica no front, nesse repositório aqui: https://github.com/loft-br/realtime_r0_brazil_front. Passei para o pessoal aqui, pode reproduzir a issue lá?

**Comment by FernandaBernardo** [comment]
Corrigido! :)
